### PR TITLE
Documentation update with REST API key features and diagram

### PR DESCRIPTION
**Pull request by vsasvipul0605**
if required we can add resource links

### CODE REVIEW

**Comment by Arna-Maity** [comment]
@vsasvipul0605 Good Job. But I would like to suggest few minor changes:
1. Since the doc is in markdown format, you need to use a syntax like this to include images:
   ` `
   Go through this link for more info: https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf
2. It will be a good idea to create a separate directory by the name **docs/** in the repo root to store all the documentation.
3. You can store all the required images in an **images/** sub-directory of the **docs/** directory.

**Comment by Arna-Maity** [comment]
That's better. One last thing before i merge in the changes, please try to **squash** all your commits into a single commit. You might not realize the advantage of doing this just yet, but i am sure you'll realize it gradually, when you go on to work on larger projects.
For doing this you'll need to use git bash.

To know more about basic git commands go through this:
https://github.com/Arna-Maity/hello-world-git

You can go through this link to know how to squash commits using **interactive rebase**:
 https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by vsasvipul0605** [comment]
hey, can you merge this time. I'll take care of this from next time.

**Comment by Arna-Maity** [comment]
@vsasvipul0605 Sure, but try to follow the above guidelines next time onwards, as it will help you in future. Merging Now.
Also make a comment on #1 so that i can assign it to you.

**Pull request merged**
